
## Project information
site_name: UW STAB

theme:
  name: material
  logo: assets/UW_logo.svg
  features:
    - navigavtion.indexes
    - navigation.tabs            # Static upper section tabs (exist)
    - navigation.tabs.sticky
    - navigation.top # back to top button

nav:
- Home: index.md
- About Us: history.md
- People: team.md
- Schedule: schedule.md
- Blog: blog.md

markdown_extensions: 
  - attr_list
  - md_in_html